# Generated by Django 5.1.1 on 2024-09-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders_order',
        ),
    ]
