# Generated by Django 5.1.1 on 2024-09-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
