# Generated by Django 5.1.1 on 2024-09-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
